# Compile all the Java files
all: 
	mkdir bin
	javac -d bin src/*.java

# Run the 1st test
test1: 
	java -cp bin Test1 && exit

# Run the 2nd test
test2:
	java -cp bin Test2 && exit

# Run the 3rd test
test3:
	java -cp bin Test3 && exit

# Run the 4th test
test4:
	java -cp bin Test4 && exit

# Run the 5th test
test5:
	java -cp bin Test5 && exit

# Clean up compiled files
clean:
	rm -rf bin
